/**
  * Copyright (c) 2019 Nuclei Limited. All rights reserved.
  *
  * SPDX-License-Identifier: Apache-2.0
  *
  * Licensed under the Apache License, Version 2.0 (the License); you may
  * not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  * www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an AS IS BASIS, WITHOUT
  * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  */

#ifndef __NS__BASIC_TIMER_H__
#define __NS__BASIC_TIMER_H__

/**
  * \file     ns_basic_timer.h
  * \brief    Basic TIMER feature API header file for Nuclei SDK
  */

#ifdef __cplusplus
extern "C" {
#endif

#include "ns.h"

/* constants definitions */
/* TIMER init parameter struct definitions */
typedef struct {
    uint32_t prescaler;                                                       /*!< prescaler value */
    uint32_t period;                                                          /*!< period value */
} Basic_TIMER_Init_TypeDef;

#define BASIC_TIMER_CR1_OFFSET                                                0x0 /*!< Timer Control register1. */
#define BASIC_TIMER_CR2_OFFSET                                                0x4 /*!< Timer Control register2. */
#define BASIC_TIMER_DIER_OFFSET                                               0xc /*!< DMA/Interrupt enable register. */
#define BASIC_TIMER_SR_OFFSET                                                 0x10 /*!< Status register. */
#define BASIC_TIMER_EGR_OFFSET                                                0x14 /*!< Event generation register. */
#define BASIC_TIMER_CNT_OFFSET                                                0x24 /*!< Counter register. */
#define BASIC_TIMER_PSC_OFFSET                                                0x28 /*!< Prescaler register. */
#define BASIC_TIMER_ARR_OFFSET                                                0x2c /*!< Auto reload register. */
#define BASIC_TIMER_IP_VERSION_OFFSET                                         0x30 /*!< IP version. */

 /* ===== BASIC TIMER CR1 Register definition ===== */
#define BASIC_TIMER_CR1_CEN                          BIT(0)                                      /*!< Counter enable -1'b0:    Counter_disabled: Counter disabled -1'b1:    Counter_enabled: Counter enabled Note: when an update event occurs. This bit is cleared automatically in one-pulse mode. */
#define BASIC_TIMER_CR1_CEN_OFS                      0U                                          /*!< BASIC TIMER CR1: CEN Bit Offset */
#define BASIC_TIMER_CR1_CEN_VAL(regval)                  (BIT(0) & ((uint32_t)(regval) << 0))        /*!< BASIC TIMER CR1: CEN Bit Value */  
#define BASIC_TIMER_CR1_CEN_COUNTER_DISABLED              0x0UL                                                 /*!< COUNTER_DISABLED */
#define BASIC_TIMER_CR1_CEN_COUNTER_ENABLED               BIT(0)                                                   /*!< COUNTER_ENABLED */

/**
  * \brief Check the BASIC_TIMER cr1 cen bit parameters.
  * \param regval bit value to be checked.
  * \retval 0 This is not a valid cen bit.
  * \retval 1 This is a valid cen bit.
  */
#define IS_BASIC_TIMER_CR1_CEN(regval)                    (\
                                              ((regval) == BASIC_TIMER_CR1_CEN_COUNTER_DISABLED    ) || \
                                              ((regval) == BASIC_TIMER_CR1_CEN_COUNTER_ENABLED     )  \
                                                 )

#define BASIC_TIMER_CR1_UPD_EVT_DIS                  BIT(1)                                      /*!< Update event disable -1'b0:    event_enabled:Update event enabled. The update event is generated by one of the following events: event1: Counter overflow. event2: Setting the UG bit. Buffered registers are then loaded with their preload values. -1'b1:   event_disabled: Update event disabled. The Update event is not generated, shadow registers(ARR/PSC) keep their value.  Note:  1.The time_counter is reseted by overflow or UG bit. 2.The prescaler counter is reseted by UG bit. */
#define BASIC_TIMER_CR1_UPD_EVT_DIS_OFS              1U                                          /*!< BASIC TIMER CR1: UPD_EVT_DIS Bit Offset */
#define BASIC_TIMER_CR1_UPD_EVT_DIS_VAL(regval)          (BIT(1) & ((uint32_t)(regval) << 1))        /*!< BASIC TIMER CR1: UPD_EVT_DIS Bit Value */  
#define BASIC_TIMER_CR1_UPD_EVT_DIS_EVENT_ENABLED             0x0UL                                                 /*!< EVENT_ENABLED */
#define BASIC_TIMER_CR1_UPD_EVT_DIS_EVENT_DISABLED             BIT(1)                                                   /*!< EVENT_DISABLED */

/**
  * \brief Check the BASIC_TIMER cr1 upd_evt_dis bit parameters.
  * \param regval bit value to be checked.
  * \retval 0 This is not a valid upd_evt_dis bit.
  * \retval 1 This is a valid upd_evt_dis bit.
  */
#define IS_BASIC_TIMER_CR1_UPD_EVT_DIS(regval)            (\
                                      ((regval) == BASIC_TIMER_CR1_UPD_EVT_DIS_EVENT_ENABLED       ) || \
                                      ((regval) == BASIC_TIMER_CR1_UPD_EVT_DIS_EVENT_DISABLED      )  \
                                                 )

#define BASIC_TIMER_CR1_UPD_EVT_SEL                  BIT(2)                                      /*!< Update event source select -1'b0:    any_enabled: Any of the following events generates an update interrupt or DMA request if enabled. These events can be: event1: Counter overflow.  event2: Setting the UG bit by software. -1'b1:    only_enabled: Only counter overflow generates an update interrupt or DMA request if enabled.  */
#define BASIC_TIMER_CR1_UPD_EVT_SEL_OFS              2U                                          /*!< BASIC TIMER CR1: UPD_EVT_SEL Bit Offset */
#define BASIC_TIMER_CR1_UPD_EVT_SEL_VAL(regval)          (BIT(2) & ((uint32_t)(regval) << 2))        /*!< BASIC TIMER CR1: UPD_EVT_SEL Bit Value */  
#define BASIC_TIMER_CR1_UPD_EVT_SEL_ANY_ENABLED             0x0UL                                                 /*!< ANY_ENABLED */
#define BASIC_TIMER_CR1_UPD_EVT_SEL_ONLY_ENABLED             BIT(2)                                                   /*!< ONLY_ENABLED */

/**
  * \brief Check the BASIC_TIMER cr1 upd_evt_sel bit parameters.
  * \param regval bit value to be checked.
  * \retval 0 This is not a valid upd_evt_sel bit.
  * \retval 1 This is a valid upd_evt_sel bit.
  */
#define IS_BASIC_TIMER_CR1_UPD_EVT_SEL(regval)            (\
                                      ((regval) == BASIC_TIMER_CR1_UPD_EVT_SEL_ANY_ENABLED         ) || \
                                      ((regval) == BASIC_TIMER_CR1_UPD_EVT_SEL_ONLY_ENABLED        )  \
                                                 )

#define BASIC_TIMER_CR1_OPM                          BIT(3)                                      /*!< One pulse mode. -1'b0:    disabled:Counter is not stopped at update event. -1'b1:    enabled:Counter stops counting at the next update event, and clearing the bit CEN meanwhile. */
#define BASIC_TIMER_CR1_OPM_OFS                      3U                                          /*!< BASIC TIMER CR1: OPM Bit Offset */
#define BASIC_TIMER_CR1_OPM_VAL(regval)                  (BIT(3) & ((uint32_t)(regval) << 3))        /*!< BASIC TIMER CR1: OPM Bit Value */  
#define BASIC_TIMER_CR1_OPM_DISABLED                      0x0UL                                                 /*!< DISABLED */
#define BASIC_TIMER_CR1_OPM_ENABLED                       BIT(3)                                                   /*!< ENABLED */

/**
  * \brief Check the BASIC_TIMER cr1 opm bit parameters.
  * \param regval bit value to be checked.
  * \retval 0 This is not a valid opm bit.
  * \retval 1 This is a valid opm bit.
  */
#define IS_BASIC_TIMER_CR1_OPM(regval)                    (\
                                              ((regval) == BASIC_TIMER_CR1_OPM_DISABLED            ) || \
                                              ((regval) == BASIC_TIMER_CR1_OPM_ENABLED             )  \
                                                 )

#define BASIC_TIMER_CR1_AUTO_BUFFER_EN               BIT(7)                                      /*!< Auto-buffer enable -1'b0:    disabled: TIMx_ARR register is not buffered -1'b1:    enabled:TIMx_ARR register is buffered */
#define BASIC_TIMER_CR1_AUTO_BUFFER_EN_OFS           7U                                          /*!< BASIC TIMER CR1: AUTO_BUFFER_EN Bit Offset */
#define BASIC_TIMER_CR1_AUTO_BUFFER_EN_VAL(regval)       (BIT(7) & ((uint32_t)(regval) << 7))        /*!< BASIC TIMER CR1: AUTO_BUFFER_EN Bit Value */  
#define BASIC_TIMER_CR1_AUTO_BUFFER_EN_DISABLED             0x0UL                                                 /*!< DISABLED */
#define BASIC_TIMER_CR1_AUTO_BUFFER_EN_ENABLED             BIT(7)                                                   /*!< ENABLED */

/**
  * \brief Check the BASIC_TIMER cr1 auto_buffer_en bit parameters.
  * \param regval bit value to be checked.
  * \retval 0 This is not a valid auto_buffer_en bit.
  * \retval 1 This is a valid auto_buffer_en bit.
  */
#define IS_BASIC_TIMER_CR1_AUTO_BUFFER_EN(regval)         (\
                                   ((regval) == BASIC_TIMER_CR1_AUTO_BUFFER_EN_DISABLED            ) || \
                                   ((regval) == BASIC_TIMER_CR1_AUTO_BUFFER_EN_ENABLED             )  \
                                                 )

 /* ===== BASIC TIMER CR2 Register definition ===== */
#define BASIC_TIMER_CR2_MMS_MASK                     BITS(4,6)                                   /*!< BASIC TIMER CR2: MMS Bit Mask */  
#define BASIC_TIMER_CR2_MMS_OFS                      4U                                          /*!< BASIC TIMER CR2: MMS Bit Offset */
#define BASIC_TIMER_CR2_MMS(regval)                  (BITS(4,6) & ((uint32_t)(regval) << 4))        /*!< BASIC TIMER CR2: MMS Bit Value */  
#define BASIC_TIMER_CR2_MMS_RESET                         BASIC_TIMER_CR2_MMS(0)                                                   /*!< RESET */
#define BASIC_TIMER_CR2_MMS_ENABLE                        BASIC_TIMER_CR2_MMS(1)                                                   /*!< ENABLE */
#define BASIC_TIMER_CR2_MMS_UPDATE                        BASIC_TIMER_CR2_MMS(2)                                                   /*!< UPDATE */

/**
  * \brief Check the BASIC_TIMER cr2 mms bits parameters.
  * \param regval bits value to be checked.
  * \retval 0 This is not a valid mms bits.
  * \retval 1 This is a valid mms bits.
  */
#define IS_BASIC_TIMER_CR2_MMS(regval)                    (\
                                              ((regval) == BASIC_TIMER_CR2_MMS_RESET               ) || \
                                              ((regval) == BASIC_TIMER_CR2_MMS_ENABLE              ) || \
                                              ((regval) == BASIC_TIMER_CR2_MMS_UPDATE              )  \
                                                 )

 /* ===== BASIC TIMER DIER Register definition ===== */
#define BASIC_TIMER_DIER_UIE                          BIT(0)                                      /*!< Enable the update event used as basic_timer interrupt -1'b0:    disabled: When the update event is set, don't send interrupt -1'b1:    enabled: When the update event is set, send interrupt */
#define BASIC_TIMER_DIER_UIE_OFS                      0U                                          /*!< BASIC TIMER DIER: UIE Bit Offset */
#define BASIC_TIMER_DIER_UIE_VAL(regval)                  (BIT(0) & ((uint32_t)(regval) << 0))        /*!< BASIC TIMER DIER: UIE Bit Value */  
#define BASIC_TIMER_DIER_UIE_DISABLED                      0x0UL                                                /*!< DISABLED */
#define BASIC_TIMER_DIER_UIE_ENABLED                       BIT(0)                                                   /*!< ENABLED */

/**
  * \brief Check the BASIC_TIMER dier uie bit parameters.
  * \param regval bit value to be checked.
  * \retval 0 This is not a valid uie bit.
  * \retval 1 This is a valid uie bit.
  */
#define IS_BASIC_TIMER_DIER_UIE(regval)                    (\
                                              ((regval) == BASIC_TIMER_DIER_UIE_DISABLED            ) || \
                                              ((regval) == BASIC_TIMER_DIER_UIE_ENABLED             )  \
                                                 )

#define BASIC_TIMER_DIER_UDE                          BIT(8)                                      /*!< Enable the update event used as dma request -1'b0:    disabled: When the update event is set, don't send interrupt -1'b1:    enabled: When the update event is set, send interrupt */
#define BASIC_TIMER_DIER_UDE_OFS                      8U                                          /*!< BASIC TIMER DIER: UDE Bit Offset */
#define BASIC_TIMER_DIER_UDE_VAL(regval)                  (BIT(8) & ((uint32_t)(regval) << 8))        /*!< BASIC TIMER DIER: UDE Bit Value */  
#define BASIC_TIMER_DIER_UDE_DISABLED                      0x0UL                                                /*!< DISABLED */
#define BASIC_TIMER_DIER_UDE_ENABLED                       BIT(8)                                                   /*!< ENABLED */

/**
  * \brief Check the BASIC_TIMER dier ude bit parameters.
  * \param regval bit value to be checked.
  * \retval 0 This is not a valid ude bit.
  * \retval 1 This is a valid ude bit.
  */
#define IS_BASIC_TIMER_DIER_UDE(regval)                    (\
                                              ((regval) == BASIC_TIMER_DIER_UDE_DISABLED            ) || \
                                              ((regval) == BASIC_TIMER_DIER_UDE_ENABLED             )  \
                                                 )

 /* ===== BASIC TIMER SR Register definition ===== */
#define BASIC_TIMER_SR_EVT_STATUS                   BIT(0)                                      /*!< Update event status -1'b0: No update event occurred. -1'b1: Update event interrupt pending. This bit is set by hardware when the update event is set. Note: This bit is set by hardware on an update event. It is cleared by software. */
#define BASIC_TIMER_SR_EVT_STATUS_OFS               0U                                          /*!< BASIC TIMER SR: EVT_STATUS Bit Offset */
#define BASIC_TIMER_SR_EVT_STATUS_VAL(regval)           (BIT(0) & ((uint32_t)(regval) << 0))        /*!< BASIC TIMER SR: EVT_STATUS Bit Value */  

/**
  * \brief Check the BASIC_TIMER sr evt_status bit parameters.
  * \param regval bit value to be checked.
  * \retval 0 This is not a valid evt_status bit.
  * \retval 1 This is a valid evt_status bit.
  */
#define IS_BASIC_TIMER_SR_EVT_STATUS(regval)             (\
                                                 )

 /* ===== BASIC TIMER EGR Register definition ===== */
#define BASIC_TIMER_EGR_UG                           BIT(0)                                      /*!< Update generation This bit can be set by software, it is automatically cleared by hardware. -1'b0: No action -1'b1: Update event is generated by software */
#define BASIC_TIMER_EGR_UG_OFS                       0U                                          /*!< BASIC TIMER EGR: UG Bit Offset */
#define BASIC_TIMER_EGR_UG_VAL(regval)                   (BIT(0) & ((uint32_t)(regval) << 0))        /*!< BASIC TIMER EGR: UG Bit Value */  
#define BASIC_TIMER_EGR_UG_NO                             0x0UL                                                 /*!< NO */
#define BASIC_TIMER_EGR_UG_UPDATE                         BIT(0)                                                   /*!< UPDATE */

/**
  * \brief Check the BASIC_TIMER egr ug bit parameters.
  * \param regval bit value to be checked.
  * \retval 0 This is not a valid ug bit.
  * \retval 1 This is a valid ug bit.
  */
#define IS_BASIC_TIMER_EGR_UG(regval)                     (\
                                               ((regval) == BASIC_TIMER_EGR_UG_NO                  ) || \
                                               ((regval) == BASIC_TIMER_EGR_UG_UPDATE              )  \
                                                 )

 /* ===== BASIC TIMER CNT Register definition ===== */
#define BASIC_TIMER_CNT_CNT_MASK                     BITS(0,31)                                   /*!< BASIC TIMER CNT: CNT Bit Mask */  
#define BASIC_TIMER_CNT_CNT_OFS                      0U                                          /*!< BASIC TIMER CNT: CNT Bit Offset */
#define BASIC_TIMER_CNT_CNT(regval)                  (BITS(0,31) & ((uint32_t)(regval) << 0))        /*!< BASIC TIMER CNT: CNT Bit Value */  
 
 /* ===== BASIC TIMER PSC Register definition ===== */
#define BASIC_TIMER_PSC_PSC_MASK                     BITS(0,15)                                   /*!< BASIC TIMER PSC: PSC Bit Mask */  
#define BASIC_TIMER_PSC_PSC_OFS                      0U                                          /*!< BASIC TIMER PSC: PSC Bit Offset */
#define BASIC_TIMER_PSC_PSC(regval)                  (BITS(0,15) & ((uint32_t)(regval) << 0))        /*!< BASIC TIMER PSC: PSC Bit Value */  
 
 /* ===== BASIC TIMER ARR Register definition ===== */
#define BASIC_TIMER_ARR_ARR_MASK                     BITS(0,31)                                   /*!< BASIC TIMER ARR: ARR Bit Mask */  
#define BASIC_TIMER_ARR_ARR_OFS                      0U                                          /*!< BASIC TIMER ARR: ARR Bit Offset */
#define BASIC_TIMER_ARR_ARR(regval)                  (BITS(0,31) & ((uint32_t)(regval) << 0))        /*!< BASIC TIMER ARR: ARR Bit Value */  
 
 /* ===== BASIC TIMER IP_VERSION Register definition ===== */
#define BASIC_TIMER_IP_VERSION_VERSION_NUM                  BITS(0,31)                

void Basic_Timer_StructParaInit(Basic_TIMER_Init_TypeDef* initpara);
void Basic_Timer_Init(BASIC_TIMER_TypeDef* timer, Basic_TIMER_Init_TypeDef* initpara);
void Basic_Timer_Enable(BASIC_TIMER_TypeDef* timer);
void Basic_Timer_Disable(BASIC_TIMER_TypeDef* timer);
void Basic_Timer_AutoReloadShadowEnable(BASIC_TIMER_TypeDef* timer);
void Basic_Timer_AutoReloadShadowDisable(BASIC_TIMER_TypeDef* timer);
void Basic_Timer_UpdateEventEnable(BASIC_TIMER_TypeDef* timer);
void Basic_Timer_UpdateEventDisable(BASIC_TIMER_TypeDef* timer);
void Basic_Timer_PrescalerConfig(BASIC_TIMER_TypeDef* timer, uint32_t prescaler, uint32_t pscreload);
void Basic_Timer_AutoReloadValueConfig(BASIC_TIMER_TypeDef* timer, uint32_t autoreload);
void Basic_Timer_CounterValueConfig(BASIC_TIMER_TypeDef* timer, uint32_t counter);
uint32_t Basic_Timer_CounterRead(BASIC_TIMER_TypeDef* timer);
uint32_t Basic_Timer_PrescalerRead(BASIC_TIMER_TypeDef* timer);
void Basic_Timer_SinglePulseModeConfig(BASIC_TIMER_TypeDef* timer, uint32_t spmode);
void Basic_Timer_UpdateSourceConfig(BASIC_TIMER_TypeDef* timer, uint32_t update);
void Basic_Timer_DmaEnable(BASIC_TIMER_TypeDef* timer, uint32_t dma);
void Basic_Timer_DmaDisable(BASIC_TIMER_TypeDef* timer, uint32_t dma);
void Basic_Timer_EventSoftwareGenerate(BASIC_TIMER_TypeDef* timer, uint32_t event);
void Basic_Timer_MasterOutputTriggerSourceSelect(BASIC_TIMER_TypeDef* timer, uint32_t outrigger);
void Basic_Timer_InterruptEnable(BASIC_TIMER_TypeDef* timer, uint32_t interrupt);
void Basic_Timer_InterruptDisable(BASIC_TIMER_TypeDef* timer, uint32_t interrupt);
FlagStatus Basic_Timer_InterruptFlagGet(BASIC_TIMER_TypeDef* timer, uint32_t interrupt);
void Basic_Timer_InterruptFlagClear(BASIC_TIMER_TypeDef* timer, uint32_t interrupt);
FlagStatus Basic_Timer_FlagGet(BASIC_TIMER_TypeDef* timer, uint32_t flag);
void Basic_Timer_FlagClear(BASIC_TIMER_TypeDef* timer, uint32_t flag);

#ifdef __cplusplus
}
#endif

#endif /* NS__BASIC_TIMER_H */
