TARGET = utb_mac_rx_smoke

NUCLEI_SDK_ROOT = ../../..

SRCDIRS = .
INCDIRS = .

COMMON_FLAGS := -O2

include $(NUCLEI_SDK_ROOT)/platform/utb_port/build.mk
include $(NUCLEI_SDK_ROOT)/platform/utb_hal/build.mk

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
