TARGET = ql25_amp_slave
RTOS = FreeRTOS

NUCLEI_SDK_ROOT = ../../..

SRCDIRS = .
INCDIRS = .

include $(NUCLEI_SDK_ROOT)/platform/ipc/build.mk
include $(NUCLEI_SDK_ROOT)/platform/utb_hal/build.mk

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
