TARGET = SPI_qspi1_spi_flash_fatfs

NUCLEI_SDK_ROOT = ../../../../..

SRCDIRS = .

INCDIRS = .

COMPONENTS := NOR_FLASH

MIDDLEWARE := FATFS
COMMON_FLAGS := -Os

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
