TARGET = utb_osal_demo
RTOS = FreeRTOS

NUCLEI_SDK_ROOT = ../../..

SRCDIRS = .
INCDIRS = .

include $(NUCLEI_SDK_ROOT)/platform/utb_port/build.mk
include $(NUCLEI_SDK_ROOT)/platform/utb_osal/build.mk
include $(NUCLEI_SDK_ROOT)/platform/utb_hal/build.mk

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
