#ifndef __NS_CORE1_FEATURE__
#define __NS_CORE1_FEATURE__
#define CFG_GEN_CPUFEATURE 1
#define CPU_ISA "rv32imafu_zicsr_zicntr_zifencei_zicond_zilsd_zclsd_zca_zcb_zcf_zcmp_zcmt_zba_zbb_zbs_smepmp"
#define CFG_CPU_NAME "xunlian"
#define CFG_CPU_VERSION "v5.5.0"
#define CFG_CPU_REV 0x50500
#define CFG_E16 0
#define CFG_XLEN 32
#define CFG_FLEN 32
// cpu feature 
#define CFG_HAS_EXCP
#define CFG_HAS_PMA
#define CFG_HAS_PMA_MACRO
#define CFG_PMA_CSR_NUM 8
#define CFG_PMA_SEC_CSR_NUM 0
#define CFG_CPU_IS_300
#define CFG_MEM_TYPE_ICB
#define CFG_IREGION_BASE_ADDR 0x00000000
#define CFG_MUL_2CYC
#define CFG_HAS_ADV_DIV
#define CFG_HAS_PMP
#define CFG_PMP_ENTRY_NUM 16
#define CFG_PMP_GRAIN 10
#define CFG_HAS_STACK_CHECK
#define CFG_HAS_ISA_ZBA_ZBB_ZBS
#define CFG_HAS_CODE_SIZE_DEC_EXT
#define CFG_HAS_ISA_ZILSD
#define CFG_HAS_DEBUG
#define CFG_DEBUG_TRIGM_NUM 4
#define CFG_HAS_SBA
#define CFG_DEBUG_TAP_AON
#define CFG_HAS_ICACHE
#define CFG_ICACHE_ADDR_WIDTH 15
#define CFG_HAS_ILM
#define CFG_ILM_BASE_ADDR 0x09000000
#define CFG_ILM_ADDR_WIDTH 16
#define CFG_ILM_ITF_TYPE_SRAM
#define CFG_HAS_DLM
#define CFG_DLM_BASE_ADDR 0x09010000
#define CFG_DLM_ADDR_WIDTH 15
#define CFG_DLM_ITF_TYPE_SRAM
#define CFG_HAS_SLAVE_PORT
#define CFG_DEVICE_REGION_NUM 1
#define CFG_DEVICE_REGION0_BASE 0x10000000
#define CFG_DEVICE_REGION0_MASK 0xf0000000
#define CFG_NC_REGION_NUM 0
#define CFG_CACHEABLE_REGION_NUM 0
#define CFG_IRQ_NUM 128
#define CFG_CLICINTCTLBITS 3
#define CFG_HAS_DUAL_ISSUE
#define CFG_LSU_DW 64
#define CFG_IFU_CUT_TIMING
#define CFG_MEM_CUT_TIMING
#define CFG_FPU_SINGLE
#define CFG_3CYC_FPU
#define CFG_RAM_DFT_IN_WID 0
#define CFG_RAM_DFT_OUT_WID 0
#define CFG_HAS_DEBUG_PRIVATE
#define CFG_HAS_CLIC_INSIDE_CORE
#define CFG_HAS_RST_OPT
#define CFG_CLIC_FLOP_OUT
#define CFG_HAS_CLIC
#define CFG_HAS_AMO
#define CFG_REGFILE_RST
#define CFG_REGFILE_2WP
#define CFG_REGNUM_IS_32
#define CFG_INDEP_MULDIV
#define CFG_DEDICATED_AGU
#define CFG_MISALIGNED_ACCESS
#define CFG_ADDR_SIZE_IS_32
#define CFG_HAS_BMU
#define CFG_HAS_ZILSD
#define CFG_HAS_PAIR_REGFILE
#define CFG_HAS_RD_HI
#define CFG_HAS_RF_CRC 0
#define CFG_HAS_ASILB 0
#define CFG_HAS_REMAP 0
#define CFG_HAS_BASE_ISA_EXTENSION
#define CFG_HAS_ZC_EXT
#define CFG_HAS_ZICOND_EXTENSION
#define CFG_HAS_PREFETCH
#define CFG_ILM_LATENCY 2
#define CFG_HAS_IRQ_BOOST
#define CFG_HAS_UMODE
#define CFG_HAS_SMEPMP
#define CFG_HAS_PMONITOR
#define CFG_XLEN_IS_32
#define CFG_HAS_ECLIC
#define CFG_HAS_CLIC_EDGE
#define CFG_CLIC_VERSION 1
#define CFG_HAS_STACKSAFE
#define CFG_HAS_2_WIRE_DBG
#define CFG_HAS_DEBUG13
#define CFG_HAS_DEBUG_NEW
#define CFG_HAS_TRIGM
#define CFG_HAS_SBA_IN_CORE
#define CFG_SYSMEM_DATA_WIDTH_IS_32
#define CFG_HAS_MEM_ITF
#define CFG_LSU_ACCESS_ILM
#define CFG_HAS_LM 1
#define CFG_HAS_LM_SLAVE
#define CFG_HAS_BPU
#define CFG_HAS_DYNAMIC_BPU
#define CFG_PC_HASH_WIDTH 7
#define CFG_BHT_ENTRY_WIDTH 7
#define CFG_BHT_GHR_W 8
#define CFG_HAS_DEVICE
#define CFG_HAS_NCDEV_REG
#define CFG_HAS_NC
#define CFG_LINE_BYTES 32
#define CFG_HAS_CACHE
#define CFG_HAS_IOCC
#define CFG_HAS_MULDIV
#define CFG_HAS_FPU
#define CFG_HAS_FSIM
#define CFG_OITF_DEPTH_IS_6
#define CFG_HAS_FCSR_OUTPUT
#define CFG_HAS_LBIU
#define CFG_PPI_ADDR_WIDTH 20
#define CFG_PPI_BASE_ADDR 0x10000000
#define CFG_TMR_PRIVATE
#define CFG_TMR_BASE_ADDR 0x30000
#define CFG_SPMP_ENTRY_NUM 0
#define CFG_ILM_DATA_WIDTH 32
#define CFG_L1D_PREFETCH_VERSION 4
// evalsoc feature 
#define EVALSOC_PERIPS_BASE 0x10000000
#define EVALSOC_FLASH_XIP_BASE 0x20000000
#define EVALSOC_FLASH_XIP_ADDR_WIDTH 28
#define EVALSOC_SYSMEM_BASE 0xa0000000
#define EVALSOC_SYSMEM_ADDR_WIDTH 28
#define EVALSOC_DLM_DATA_WIDTH 32
#define EVALSOC_DLM_WMSK_WIDTH 4
#define EVALSOC_DLM_AW_LSB 2
#define EVALSOC_HAS_CPU_RAM_WRAPPER
#define EVALSOC_VERSION_IS_2
#define EVALSOC_HAS_BIU2ILM
#define EVALSOC_HAS_BIU2DLM
#define EVALSOC_HAS_SUBSYS_LM 1
#define EVALSOC_SYSMEM_DATA_WIDTH 32
#define EVALSOC_HAS_UART_MODEL
#define EVALSOC_HAS_IRAM_DRAM
#define EVALSOC_IRAM_BASE_ADDR 0x70000000
#define EVALSOC_IRAM_DATA_WIDTH 32
#define EVALSOC_IRAM_WMSK_WIDTH 4
#define EVALSOC_IRAM_AW_LSB 2
#define EVALSOC_IRAM_ADDR_WIDTH 15
#define EVALSOC_DRAM_BASE_ADDR 0x78000000
#define EVALSOC_DRAM_DATA_WIDTH 32
#define EVALSOC_DRAM_WMSK_WIDTH 4
#define EVALSOC_DRAM_AW_LSB 2
#define EVALSOC_DRAM_ADDR_WIDTH 15
#define EVALSOC_IRAM_RAM_DW 32
#define EVALSOC_IRAM_RAM_MW 4
#define EVALSOC_IRAM_RAM_DP 8192
#define EVALSOC_IRAM_RAM_AW 13
#define EVALSOC_DRAM_RAM_DW 32
#define EVALSOC_DRAM_RAM_MW 4
#define EVALSOC_DRAM_RAM_DP 8192
#define EVALSOC_DRAM_RAM_AW 13
#define EVALSOC_HAS_SUBSYS_MISC
#define EVALSOC_HAS_DDR
#endif
