TARGET = SPI_qspi3_spi_sdcard_fatfs

NUCLEI_SDK_ROOT = ../../../../..

SRCDIRS = .

INCDIRS = .

COMPONENTS := SPI_SDCard

MIDDLEWARE := FATFS
COMMON_FLAGS := -Os

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
